language: android

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules

install: #1.2
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
- export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
- nvm install v8.11.0
- nvm use
- npm install
- npm install -g yarn
- yarn
- cd android && bundle install

android: #1.3
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16

script: 
- yarn release:android:testers
