branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.cache/yarn"

before_install:
  - openssl aes-256-cbc -K $encrypted_c1476ebca826_key -iv $encrypted_c1476ebca826_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - nvm install v8.11.0
  - nvm use
  - npm install
  - npm install -g yarn
  - yarn
  - yarn extractcredentials

matrix:
  include:
    - language: objective-c
      osx_image: xcode9.3
      install:
        - brew tap wix/brew
        - brew install applesimutils
      script:
        - yarn test:lint
        - yarn test:jsdoc
        - yarn test:flow
        - yarn test:jest
        - detox build --configuration ios.sim.release
        - yarn test:featuresrelease
    - language: android
      jdk: oraclejdk8
      cache:
        directories:
          - "$HOME/.gradle/caches/2.8"
          - "$HOME/.gradle/caches/jars-1"
          - "$HOME/.gradle/daemon"
          - "$HOME/.gradle/native"
          - "$HOME/.gradle/wrapper"
      install:
        - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;27.0.3"
        - cd android && bundle install
      android:
        components:
          - tools
          - build-tools-23.0.1
          - android-23
          - platform-tools
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
          - extra-android-support
      script:
        - yarn release:android:testers
