language: android

branches:
  only:
  - master

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules

install: #1.2
- nvm install v8.11.0
- nvm use
- npm install
- npm install -g yarn
- yarn
- cd android && bundle install

android: #1.3
  components:
  - tools
  - build-tools-23.0.1
  - android-23
  - platform-tools
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
  - extra-android-support

script: 
- yarn release:android:testers
